jobs:
  lib:
    source:
      localFolder: ./
      project: BenchmarkLibrary2/BenchmarkLibrary2.csproj
    variables:
      filter: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filter}} --memory
    options:
      benchmarkDotNet: true  

scenarios:
  runbenchmarks:
    application:
      job: lib
      variables:
        filter: "*Benchmark*"

profiles:
  local:
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
